.\"
.\" eom manual page.
.\" (C) 2013 Scott Balneaves (sbalneav@mate-desktop.org)
.\"
.TH EOM 1 "MATE"
.SH NAME
eom \- Eye of Mate image viewer
.SH SYNOPSIS
.B eom [\-\-fullscreen] [\-\-disable-image-collection] [\-\-slide-show] [\-\-new instance]
.SH DESCRIPTION
The \fIeom\fP program allows you to view and perform some rudimentary image manipulation operations (rotate, flip, etc.).
desktop.
.SH OPTIONS
.TP
.I \-\-fullscreen
Start eom in fullscreen mode.
.TP
.I \-\-disable-image-collection
Disable image collection.
.TP
.I \-\-slide-show
Open in slideshow mode.
.TP
.I \-\-new-instance
Start a new instance instead of reusing an existing one.
.SH BUGS
If you find bugs in the \fIeom\fP program, please report
these on https://github.com/mate-desktop/eom/issues.
