##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/eom
    - appstream-glib
    - autoconf-archive
    - clang
    - exempi
    - gcc
    - git
    - gobject-introspection
    - imagemagick
    - itstool
    - lcms2
    - libexif
    - libjpeg-turbo
    - libpeas
    - make
    - mate-desktop
    - mate-common
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/eom
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjpeg-dev
    - liblcms2-dev
    - libmagickwand-dev
    - libmate-desktop-dev
    - libpeas-dev
    - librsvg2-dev
    - libstartup-notification0-dev
    - libxml2-dev
    - make
    - mate-common
    - shared-mime-info
    - x11proto-core-dev
    - yelp-tools
    - zlib1g-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/eom.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - desktop-file-utils
    - exempi-devel
    - gcc
    - git
    - gobject-introspection-devel
    - gtk3-devel
    - ImageMagick-devel
    - lcms2-devel
    - libappstream-glib-devel
    - libexif-devel
    - libjpeg-turbo-devel
    - libpeas-devel
    - librsvg2-devel
    - libxml2-devel
    - make
    - mate-common
    - mate-desktop-devel
    - redhat-rpm-config
    - zlib-devel

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjpeg-dev
    - liblcms2-dev
    - libmagickwand-dev
    - libmate-desktop-dev
    - libpeas-dev
    - librsvg2-dev
    - libstartup-notification0-dev
    - libxml2-dev
    - make
    - mate-common
    - shared-mime-info
    - x11proto-core-dev
    - yelp-tools
    - zlib1g-dev

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     egrep -lRZ 'G_GNUC_BEGIN_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_BEGIN_IGNORE_DEPRECATIONS/ /g'
  -     egrep -lRZ 'G_GNUC_END_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_END_IGNORE_DEPRECATIONS/ /g'
  - fi

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $(( $CPU_COUNT + 1 ))
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: eom-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
